import { ASSETS, SOURCES } from './sources.js';
import { json, save, now, record, latestBy, metricKey } from './lib.js';

const started_at=now(), run={run_id:`daily-${started_at}`,run_type:'daily',started_at,finished_at:null,success:false,updated_metrics:[],unchanged_metrics:[],failed_metrics:[],failed_sources:[],validation_errors:[]};
const market=await json('data/latest-market.json'), history=await json('history/metrics.json'); const working=[...market.metrics];
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const finiteTextNumber = value => {
  if (typeof value !== 'string' || !value.trim() || value.trim() === '.') return null;
  const parsed = Number(value.trim());
  return Number.isFinite(parsed) ? parsed : null;
};
const validObservationDate = value =>
  typeof value === 'string' && ISO_DATE.test(value) ? value : null;

async function fred(id) { const response=await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${id}`,{headers:{'User-Agent':'peibi-market-data'}}); if(!response.ok)throw Error(`FRED ${id}: ${response.status}`); const lines=(await response.text()).trim().split(/\r?\n/).slice(1).map(line=>line.split(',')); const row=lines.reverse().find(parts=>validObservationDate(parts[0])&&finiteTextNumber(parts[1])!==null); if(!row)throw Error(`FRED ${id}: no valid observation`); return {value:finiteTextNumber(row[1]),observation_date:row[0]}; }
async function update(asset_id, metric, config) { try { let found; if(config.fred) found=await fred(config.fred); else if(config.url){const response=await fetch(config.url);if(!response.ok)throw Error(`${response.status}`);const body=await response.json();const sourceDate=body.observation_date||body.updatedAt||body.timestamp; if(!sourceDate)throw Error('source did not provide observation date'); const parsedDate=new Date(sourceDate); if(Number.isNaN(parsedDate.getTime()))throw Error('invalid source observation date'); found={value:Number(body.price),observation_date:parsedDate.toISOString().slice(0,10)};} else {run.unchanged_metrics.push(`${asset_id}:${metric}`);return;}
 if(!Number.isFinite(found.value)||!validObservationDate(found.observation_date))throw Error('invalid value or observation date'); const previous=working.find(x=>x.asset_id===asset_id&&x.metric===metric); const checked=now(); const row=record({asset_id,metric,value:found.value,unit:config.unit,observation_date:found.observation_date,published_date:found.observation_date,source:config.source,source_url:config.source_url,retrieved_at:checked,latest_available_checked_at:checked,quality:'automatic verified'}); if(previous?.observation_date===row.observation_date&&previous.value===row.value){previous.latest_available_checked_at=checked;previous.retrieved_at=checked;run.unchanged_metrics.push(`${asset_id}:${metric}`);}else{const index=working.findIndex(x=>x.asset_id===asset_id&&x.metric===metric);if(index>=0)working[index]=row;else working.push(row);run.updated_metrics.push(`${asset_id}:${metric}`);} }catch(error){run.failed_metrics.push(`${asset_id}:${metric}`);run.failed_sources.push({asset_id,metric,error:String(error)});} }
for(const asset of ASSETS)for(const [metric,config] of Object.entries(SOURCES[asset.id]))if(config.mode==='auto')await update(asset.id,metric,config);
async function refreshFredDerived(asset_id, seriesId) { try { const response=await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${seriesId}`);if(!response.ok)throw Error(`FRED ${seriesId}: ${response.status}`);const points=(await response.text()).trim().split(/\r?\n/).slice(1).map(x=>x.split(',')).map(([date,value])=>({date,value:finiteTextNumber(value)})).filter(point=>validObservationDate(point.date)&&point.value!==null&&point.value>0);if(points.length<253)throw Error(`FRED ${seriesId}: insufficient valid daily observations (${points.length})`);const recent=points.slice(-253),current=recent.at(-1),returns=recent.slice(1).map((p,i)=>Math.log(p.value/recent[i].value)).filter(Number.isFinite);if(returns.length<252)throw Error(`FRED ${seriesId}: insufficient valid returns (${returns.length})`);const mean=returns.reduce((a,b)=>a+b,0)/returns.length,variance=returns.reduce((a,b)=>a+(b-mean)**2,0)/(returns.length-1),stdev=Math.sqrt(variance)*Math.sqrt(252)*100,high=Math.max(...recent.map(p=>p.value)),smaWindow=recent.slice(-200),sma200=smaWindow.reduce((a,p)=>a+p.value,0)/smaWindow.length;const derived={volatility:stdev,drawdown:(current.value/high-1)*100,trend:(current.value/sma200-1)*100};if(Object.values(derived).some(value=>!Number.isFinite(value)))throw Error(`FRED ${seriesId}: non-finite derived metric`);for(const [metric,value] of Object.entries(derived)){const prior=working.find(x=>x.asset_id===asset_id&&x.metric===metric),checked=now(),row=record({asset_id,metric,value:Number(value.toFixed(4)),unit:'%',observation_date:current.date,published_date:current.date,source:`FRED ${seriesId} derived daily history`,source_url:`https://fred.stlouisfed.org/series/${seriesId}`,retrieved_at:checked,latest_available_checked_at:checked,quality:'automatic verified calculation'});const ix=working.findIndex(x=>x.asset_id===asset_id&&x.metric===metric);if(prior?.observation_date===row.observation_date&&prior.value===row.value){prior.latest_available_checked_at=checked;prior.retrieved_at=checked;run.unchanged_metrics.push(`${asset_id}:${metric}`);}else{if(ix>=0)working[ix]=row;else working.push(row);run.updated_metrics.push(`${asset_id}:${metric}`);}}}catch(error){run.failed_metrics.push(`${asset_id}:derived_market_metrics`);run.failed_sources.push({asset_id,metric:'derived_market_metrics',error:String(error)});}}
await refreshFredDerived('nasdaq100','NASDAQ100'); await refreshFredDerived('sp500','SP500');
for(const asset of ASSETS)for(const [metric,config] of Object.entries(SOURCES[asset.id]))if(config.mode==='check_only'||(config.mode==='derived'&&asset.id==='gold'))run.unchanged_metrics.push(`${asset.id}:${metric}`);
const valid=[...working].filter(x=>Number.isFinite(x.value)); await save('data/latest-market.json',{schema_version:1,updated_at:now(),metrics:latestBy(valid)});
const known=new Set(history.records.map(metricKey));for(const row of valid)if(!known.has(metricKey(row))){history.records.push(row);known.add(metricKey(row));}await save('history/metrics.json',history);
run.finished_at=now();run.success=run.failed_metrics.length===0;const safeStamp=`${started_at.slice(0,10).replaceAll('-','')}-${started_at.slice(11,19).replaceAll(':','')}`;await save('logs/refresh-latest.json',run); await save(`logs/refresh-${safeStamp}.json`,run);
console.log(JSON.stringify(run,null,2));
if (!run.success) process.exitCode = 1;
