import { ASSETS, SOURCES } from './sources.js';
import { json, save, now, latestBy, metricKey } from './lib.js';
const started_at=now(),run={run_id:`weekly-${started_at}`,run_type:'weekly',started_at,finished_at:null,success:false,updated_metrics:[],unchanged_metrics:[],failed_metrics:[],failed_sources:[],warnings:[],validation_errors:[]};
const valuation=await json('data/latest-valuation.json'), history=await json('history/metrics.json'), overrides=await json('data/manual-overrides.json'); const next=[...valuation.metrics];
for(const asset of ASSETS)for(const [metric,config] of Object.entries(SOURCES[asset.id]))if(['manual','check_only'].includes(config.mode)){const key=`${asset.id}:${metric}`, override=overrides.metrics.find(x=>`${x.asset_id}:${x.metric}`===key);const existing=next.find(x=>`${x.asset_id}:${x.metric}`===key);const checkUrl=config.source_url||existing?.source_url;
 if(!checkUrl){run.warnings.push({asset_id:asset.id,metric,warning:'No automated source configured',source_status:'source_not_configured',status:'manual_required'});run.unchanged_metrics.push(`${key}:manual_required`);continue;}
 try{const response=await fetch(checkUrl,{method:'HEAD',redirect:'follow'});if(!response.ok)throw Error(`Source check HTTP ${response.status}`);if(override){const pos=next.findIndex(x=>`${x.asset_id}:${x.metric}`===key);const checked=now(),row={...override,retrieved_at:checked,latest_available_checked_at:checked,status:'available'};if(pos>=0)next[pos]=row;else next.push(row);run[existing?.observation_date===row.observation_date?'unchanged_metrics':'updated_metrics'].push(key);}else if(existing){existing.latest_available_checked_at=now();existing.retrieved_at=now();run.unchanged_metrics.push(key);}else{run.unchanged_metrics.push(`${key}:no_last_known_good`);}}catch(error){run.failed_metrics.push(key);run.failed_sources.push({asset_id:asset.id,metric,error:String(error)});}}
const valid=next.filter(x=>Number.isFinite(x.value));await save('data/latest-valuation.json',{schema_version:1,updated_at:now(),metrics:latestBy(valid)});const known=new Set(history.records.map(metricKey));for(const row of valid)if(!known.has(metricKey(row))){history.records.push(row);known.add(metricKey(row));}await save('history/metrics.json',history);run.finished_at=now();run.success=run.failed_metrics.length===0;await save('logs/refresh-latest.json',run);await save(`logs/${run.run_id}.json`,run);console.log(JSON.stringify(run,null,2));
if (!run.success) process.exitCode = 1;
