import { ASSETS, SOURCES } from './sources.js';
import { json, save, now, record, latestBy, metricKey } from './lib.js';

const started_at=now(), run={run_id:`daily-${started_at}`,run_type:'daily',started_at,finished_at:null,success:false,updated_metrics:[],unchanged_metrics:[],failed_metrics:[],failed_sources:[],validation_errors:[]};
const market=await json('data/latest-market.json'), history=await json('history/metrics.json'); const working=[...market.metrics];
async function fred(id) { const response=await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${id}`,{headers:{'User-Agent':'peibi-market-data'}}); if(!response.ok)throw Error(`FRED ${id}: ${response.status}`); const lines=(await response.text()).trim().split(/\r?\n/).slice(1).map(line=>line.split(',')); const row=lines.reverse().find(parts=>parts[1]&&parts[1]!=='.'); return {value:Number(row[1]),observation_date:row[0]}; }
async function update(asset_id, metric, config) { try { let found; if(config.fred) found=await fred(config.fred); else if(config.url){const response=await fetch(config.url);if(!response.ok)throw Error(`${response.status}`);const body=await response.json();found={value:Number(body.price),observation_date:new Date(body.updatedAt||body.timestamp||Date.now()).toISOString().slice(0,10)};} else {run.unchanged_metrics.push(`${asset_id}:${metric}`);return;}
 if(!Number.isFinite(found.value))throw Error('non-finite value'); const previous=working.find(x=>x.asset_id===asset_id&&x.metric===metric); const checked=now(); const row=record({asset_id,metric,value:found.value,unit:config.unit,observation_date:found.observation_date,published_date:found.observation_date,source:config.source,source_url:config.source_url,retrieved_at:checked,latest_available_checked_at:checked,quality:'automatic verified'}); if(previous?.observation_date===row.observation_date&&previous.value===row.value){previous.latest_available_checked_at=checked;previous.retrieved_at=checked;run.unchanged_metrics.push(`${asset_id}:${metric}`);}else{const index=working.findIndex(x=>x.asset_id===asset_id&&x.metric===metric);if(index>=0)working[index]=row;else working.push(row);run.updated_metrics.push(`${asset_id}:${metric}`);} }catch(error){run.failed_metrics.push(`${asset_id}:${metric}`);run.failed_sources.push({asset_id,metric,error:String(error)});} }
for(const asset of ASSETS)for(const [metric,config] of Object.entries(SOURCES[asset.id]))if(config.mode==='auto')await update(asset.id,metric,config);
async function refreshFredDerived(asset_id, seriesId) { try { const response=await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${seriesId}`);if(!response.ok)throw Error(`FRED ${seriesId}: ${response.status}`);const points=(await response.text()).trim().split(/\r?\n/).slice(1).map(x=>x.split(',')).filter(x=>Number.isFinite(Number(x[1]))).map(x=>({date:x[0],value:Number(x[1])}));const recent=points.slice(-253),current=recent.at(-1),returns=recent.slice(1).map((p,i)=>Math.log(p.value/recent[i].value)),mean=returns.reduce((a,b)=>a+b,0)/returns.length,stdev=Math.sqrt(returns.reduce((a,b)=>a+(b-mean)**2,0)/(returns.length-1))*Math.sqrt(252)*100,high=Math.max(...recent.map(p=>p.value)),sma200=recent.slice(-200).reduce((a,p)=>a+p.value,0)/200;const derived={volatility:stdev,drawdown:(current.value/high-1)*100,trend:(current.value/sma200-1)*100};for(const [metric,value] of Object.entries(derived)){const prior=working.find(x=>x.asset_id===asset_id&&x.metric===metric),checked=now(),row=record({asset_id,metric,value:Number(value.toFixed(4)),unit:'%',observation_date:current.date,published_date:current.date,source:`FRED ${seriesId} derived daily history`,source_url:`https://fred.stlouisfed.org/series/${seriesId}`,retrieved_at:checked,latest_available_checked_at:checked,quality:'automatic verified calculation'});const ix=working.findIndex(x=>x.asset_id===asset_id&&x.metric===metric);if(prior?.observation_date===row.observation_date&&prior.value===row.value){prior.latest_available_checked_at=checked;prior.retrieved_at=checked;run.unchanged_metrics.push(`${asset_id}:${metric}`);}else{if(ix>=0)working[ix]=row;else working.push(row);run.updated_metrics.push(`${asset_id}:${metric}`);}}}catch(error){run.failed_metrics.push(`${asset_id}:derived_market_metrics`);run.failed_sources.push({asset_id,metric:'derived_market_metrics',error:String(error)});}}
await refreshFredDerived('nasdaq100','NASDAQ100'); await refreshFredDerived('sp500','SP500');
for(const asset of ASSETS)for(const [metric,config] of Object.entries(SOURCES[asset.id]))if(config.mode==='check_only'||(config.mode==='derived'&&asset.id==='gold'))run.unchanged_metrics.push(`${asset.id}:${metric}`);
const valid=[...working].filter(x=>Number.isFinite(x.value)); await save('data/latest-market.json',{schema_version:1,updated_at:now(),metrics:latestBy(valid)});
const known=new Set(history.records.map(metricKey));for(const row of valid)if(!known.has(metricKey(row))){history.records.push(row);known.add(metricKey(row));}await save('history/metrics.json',history);
run.finished_at=now();run.success=run.failed_metrics.length===0;await save('logs/refresh-latest.json',run); await save(`logs/${run.run_id}.json`,run);
console.log(JSON.stringify(run,null,2));
if (!run.success) process.exitCode = 1;
